apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: ModifySet
metadata:
  name: modify-excluded-namespaces
spec:
  applyTo:
  - groups: ["constraints.gatekeeper.sh"]
    kinds: ["K8sRequiredLabels"]
    versions: ["v1beta1"]
  match:
    kinds:
    - apiGroups: ["constraints.gatekeeper.sh"]
      kinds: ["K8sRequiredLabels"]
  location: "spec.match.excludedNamespaces"
  parameters:
    assign:
      value:
      - kube-system
      - kube-public
      - kube-node-lease
      - istio-system
      - gke-connect
      - gke-system
      - gatekeeper-system
      - resource-group-system
      - config-management-system
      - config-management-monitoring
